# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfafa8e06a1362aa21b79b91c1b9b1abf4d8034dca8c2a3f113f7a8f267659f03f6fa1568cd5ab3907533fa2772ef67f6603dffdb6d43fb608ca2fc43dd2e808

test:
  secret_key_base: 17c350c2df209347367ba36cb516b74792b34ee0437b06bbda68c9b5289ed9cfa0b04ba2e48d204c422c37807b10d4b2699853b824977a6cc41e753dc6cf8770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
